POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "djkjsjkljksjl",
    "important": true
}

### 
GET http://localhost:3001/api/persons/69438b180d1d4303f50b0cdc

###
POST http://localhost:3001/api/persons
Content-Type: application/json
{
    "name": "Bri lopez",
    "number": "879-876-9090"
}